### ISSUE TITLE
RedisCluster pod template annotations are not being passed to created pods

### ISSUE THREAD

**Issue by std0** [IBM/operator-for-redis-cluster#52]
While trying to update RedisCluster pods' annotations via podAnnotations value in node-for-redis Helm chart, I discovered that they are not being passed to the resulting pods. Since podAnnotations value is directly passed to annotations in RedisCluster pod template, my hypothesis is that there is a bug in pod initialization code.

**Comment by cin** [comment]
Interesting. Thanks for the bug report. I'll take a look into it ASAP.
