### ISSUE TITLE
Pod Disruption Budget should use Min Available not Max unavailable

### ISSUE THREAD

**Issue by 5st7** [IBM/operator-for-redis-cluster#57]
## Expected Behavior
To prevent the Redis Cluster from going down, we need to make sure that only one of the pods that make up the Redis Cluster goes down.

## Current Behavior
Currently set to 1 for Max unavailable in Pod Disruption Budget, but not working properly.
```
Name:             cluster-node-for-redis
Namespace:        default
Max unavailable:  1
Selector:         app.kubernetes.io/component=database,app.kubernetes.io/instance=cluster,app.kubernetes.io/name=node-for-redis,redis-operator.k8s.io/cluster-name=cluster-node-for-redis
Status:
    Allowed disruptions:  4
    Current:              6
    Desired:              2
    Total:                3
```

## Possible Solution
Since the [Kubernetes documentation](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors) states that "only Deployment, ReplicationController, ReplicaSet, and StatefulSet can use maxUnavailable", operator-for-redis-cluster
should use MinAvailable.

```
Name:           cluster-node-for-redis
Namespace:      default
Min available:  5
Selector:       app.kubernetes.io/component=database,app.kubernetes.io/instance=cluster,app.kubernetes.io/name=node-for-redis,redis-operator.k8s.io/cluster-name=cluster-node-for-redis
Status:
    Allowed disruptions:  1
    Current:              6
    Desired:              5
    Total:                6
```

**Comment by cin** [comment]
@5st7 Thanks for the PR! I'll take a look and test it out this afternoon.
